'use strict';

// ── Data ────────────────────────────────────────────────────────────────────

const HERO_EXAMPLES = {
  hello: `// A++ — Hello World
println("Hello, World!")

let name = input("Your name: ")
println("Welcome, " + name + "!")`,

  fibonacci: `// A++ — Fibonacci
func fib(n: int) -> int {
  if n <= 1 { return n }
  return fib(n-1) + fib(n-2)
}

let i = 0
while i <= 10 {
  println("fib(" + str(i) + ") = " + str(fib(i)))
  i = i + 1
}`,

  classes: `// A++ — Classes
class Dog {
  func init(name: string) {
    self.name = name
    self.tricks = []
  }
  func learn(trick: string) {
    push(self.tricks, trick)
    println(self.name + " learned: " + trick)
  }
}

let buddy = Dog("Buddy")
buddy.learn("sit")
buddy.learn("shake")`,
};

const TARGETS = {
  cpp: {
    icon: '', name: 'C++', badge: 'Systems', color: '#38bdf8',
    desc: 'Transpile A++ to high-performance C++17. Perfect for systems programming, game dev, and embedded.',
    cmd: 'app -t cpp program.app',
    ext: 'cpp',
    code: `// Generated by A++ compiler (target: C++)
#include <iostream>
#include <string>
using namespace std;

auto fib(auto n) {
    if (n <= 1) return n;
    return fib(n-1) + fib(n-2);
}

int main() {
    for (int i = 0; i <= 10; i++) {
        cout << "fib(" << i << ") = "
             << fib(i) << endl;
    }
    return 0;
}`,
  },
  python: {
    icon: '', name: 'Python', badge: 'Scripting', color: '#fbbf24',
    desc: 'Generate clean Python 3 output. Use A++ for rapid prototyping that deploys as pure Python.',
    cmd: 'app -t python program.app',
    ext: 'py',
    code: `# Generated by A++ compiler (target: Python)

def fib(n):
    if n <= 1:
        return n
    return fib(n-1) + fib(n-2)

i = 0
while i <= 10:
    print(f"fib({i}) = {fib(i)}")
    i += 1`,
  },
  csharp: {
    icon: '', name: 'C#', badge: 'Enterprise', color: '#a78bfa',
    desc: 'Compile to clean C# for .NET, Unity, Xamarin, and enterprise applications.',
    cmd: 'app -t csharp program.app',
    ext: 'cs',
    code: `// Generated by A++ compiler (target: C#)
using System;

class Program {
    static int Fib(int n) {
        if (n <= 1) return n;
        return Fib(n-1) + Fib(n-2);
    }

    static void Main(string[] args) {
        for (int i = 0; i <= 10; i++)
            Console.WriteLine($"fib({i}) = {Fib(i)}");
    }
}`,
  },
  js: {
    icon: '🌐', name: 'JavaScript', badge: 'Web', color: '#34d399',
    desc: 'Target JavaScript for browser, Node.js, and serverless — no bundler required.',
    cmd: 'app -t js program.app',
    ext: 'js',
    code: `// Generated by A++ compiler (target: JavaScript)

function fib(n) {
    if (n <= 1) return n;
    return fib(n-1) + fib(n-2);
}

let i = 0;
while (i <= 10) {
    console.log(\`fib(\${i}) = \${fib(i)}\`);
    i++;
}`,
  },
};

const EXAMPLES = [
  {
    title: 'Hello World', file: 'hello.app',
    desc: 'The classic first program in A++.',
    code: `// A++ Hello World
println("Hello, World!")

let name = input("Your name: ")
println("Welcome, " + name + "!")

let age = 25
println("In 10 years you'll be " + str(age + 10))`,
  },
  {
    title: 'Fibonacci', file: 'fibonacci.app',
    desc: 'Recursive and iterative Fibonacci.',
    code: `// Fibonacci — recursive
func fib(n: int) -> int {
    if n <= 1 { return n }
    return fib(n - 1) + fib(n - 2)
}

// Iterative (faster)
func fibFast(n: int) -> int {
    let a = 0
    let b = 1
    let i = 2
    while i <= n {
        let t = a + b
        a = b
        b = t
        i = i + 1
    }
    return b
}

let i = 0
while i <= 12 {
    println("fib(" + str(i) + ") = " + str(fib(i)))
    i = i + 1
}`,
  },
  {
    title: 'Classes & OOP', file: 'classes.app',
    desc: 'Object-oriented programming.',
    code: `class Animal {
    func init(name: string, sound: string) {
        self.name = name
        self.sound = sound
    }
    func speak() {
        println(self.name + " says " + self.sound + "!")
    }
}

class Dog {
    func init(name: string) {
        self.name = name
        self.tricks = []
    }
    func learn(trick: string) {
        push(self.tricks, trick)
        println(self.name + " learned: " + trick)
    }
    func perform() {
        let i = 0
        while i < len(self.tricks) {
            println("  " + self.tricks[i])
            i = i + 1
        }
    }
}

let buddy = Dog("Buddy")
buddy.learn("sit")
buddy.learn("roll over")
buddy.perform()`,
  },
  {
    title: 'Sorting', file: 'sort.app',
    desc: 'Bubble sort + binary search.',
    code: `func bubbleSort(arr: list) -> list {
    let n = len(arr)
    let i = 0
    while i < n {
        let j = 0
        while j < n - i - 1 {
            if arr[j] > arr[j + 1] {
                let tmp = arr[j]
                arr[j] = arr[j + 1]
                arr[j + 1] = tmp
            }
            j = j + 1
        }
        i = i + 1
    }
    return arr
}

func binarySearch(arr: list, target: int) -> int {
    let lo = 0
    let hi = len(arr) - 1
    while lo <= hi {
        let mid = (lo + hi) / 2
        if arr[mid] == target { return mid }
        elif arr[mid] < target { lo = mid + 1 }
        else { hi = mid - 1 }
    }
    return -1
}

let nums = [64, 34, 25, 12, 22, 11, 90]
let sorted = bubbleSort(nums)
let idx = binarySearch(sorted, 25)
println("Found 25 at index: " + str(idx))`,
  },
  {
    title: 'Closures', file: 'closures.app',
    desc: 'Functional programming with lambdas.',
    code: `let add = func(a: int, b: int) -> int {
    return a + b
}

let multiply = func(a: int, b: int) -> int {
    return a * b
}

func apply(f, x: int, y: int) -> int {
    return f(x, y)
}

println(apply(add, 3, 4))       // 7
println(apply(multiply, 3, 4))  // 12

func makeCounter() {
    let count = 0
    let inc = func() {
        count = count + 1
        return count
    }
    return inc
}

let counter = makeCounter()
println(counter())  // 1
println(counter())  // 2
println(counter())  // 3`,
  },
  {
    title: 'Error Handling', file: 'errors.app',
    desc: 'Try / catch / finally.',
    code: `func safeDivide(a: float, b: float) -> float {
    if b == 0.0 {
        throw "Division by zero!"
    }
    return a / b
}

func parseNum(s: string) -> int {
    try {
        return int(s)
    } catch (e) {
        println("Parse error: " + str(e))
        return 0
    } finally {
        println("parseNum complete")
    }
}

try {
    let result = safeDivide(10.0, 0.0)
    println("Result: " + str(result))
} catch (err) {
    println("Caught error: " + str(err))
}

let n = parseNum("42")
println("Parsed: " + str(n))`,
  },
];

const INSTALL_STEPS = [
  { title: 'Clone the repository',
    lines: ['git clone https://github.com/0XOPx/aplusplus.git', 'cd aplusplus'] },
  { title: 'Build with CMake',
    lines: ['cmake -B build -DCMAKE_BUILD_TYPE=Release', 'cmake --build build --parallel'] },
  { title: 'Add to your PATH',
    lines: ['export PATH="$PWD/build:$PATH"', '# Add to ~/.bashrc or ~/.zshrc for persistence'] },
  { title: 'Run your first program',
    lines: ['echo \'println("Hello from A++!")\' > hello.app', 'app hello.app'] },
];

const QUICKREF = [
  ['app file.app',           'Run a program'],
  ['app --repl',             'Start interactive REPL'],
  ['app -t cpp file.app',    'Transpile to C++'],
  ['app -t python file.app', 'Transpile to Python'],
  ['app -t csharp file.app', 'Transpile to C#'],
  ['app -t js file.app',     'Transpile to JavaScript'],
  ['app -O2 file.app',       'Optimize (level 2)'],
  ['app --show-ast file.app','Print the AST'],
  ['app -g file.app',        'Enable debugger'],
  ['app --version',          'Show version info'],
];

// ── Syntax Highlighter ───────────────────────────────────────────────────────

const APP_KEYWORDS = new Set([
  'func','let','const','var','if','else','elif','while','for','in','return',
  'class','self','true','false','null','println','print','input','str','int',
  'float','push','pop','len','throw','try','catch','finally','and','or','not',
  'match','case','default','break','continue','import','new','delete','async',
  'await','yield','typeof','sizeof','as','is','namespace','use',
]);
const APP_TYPES = new Set(['int','float','double','string','bool','char','void','list','map','set','tuple','enum']);

const LANG_KEYWORDS = {
  cpp:    new Set(['auto','int','return','cout','endl','include','using','namespace','std','for','if','void','class']),
  python: new Set(['def','return','if','while','print','import','for','in','elif','else','and','or','not','True','False','None','class','self']),
  csharp: new Set(['static','void','int','return','class','using','for','new','string','if','var','bool','Console']),
  js:     new Set(['function','return','if','while','let','const','var','console','log','for','of','in','new','class','this']),
};

function tokenizeLine(line, lang) {
  const kws  = lang === 'app' ? APP_KEYWORDS   : (LANG_KEYWORDS[lang] || new Set());
  const typs = lang === 'app' ? APP_TYPES       : new Set();
  const tokens = [];
  let i = 0;

  while (i < line.length) {
    // Comment
    if ((line[i] === '/' && line[i+1] === '/') || line[i] === '#') {
      tokens.push({ cls: 'tok-comment', text: line.slice(i) });
      break;
    }
    // String (double quote)
    if (line[i] === '"' || line[i] === '`') {
      const q = line[i]; let j = i + 1;
      while (j < line.length && line[j] !== q) { if (line[j] === '\\') j++; j++; }
      tokens.push({ cls: 'tok-string', text: line.slice(i, j + 1) });
      i = j + 1; continue;
    }
    // String (single quote)
    if (line[i] === "'") {
      let j = i + 1;
      while (j < line.length && line[j] !== "'") { if (line[j] === '\\') j++; j++; }
      tokens.push({ cls: 'tok-string', text: line.slice(i, j + 1) });
      i = j + 1; continue;
    }
    // Word
    const wordM = line.slice(i).match(/^[a-zA-Z_]\w*/);
    if (wordM) {
      const w = wordM[0];
      let cls = 'tok-ident';
      if (kws.has(w))  cls = 'tok-keyword';
      if (typs.has(w)) cls = 'tok-type';
      tokens.push({ cls, text: w });
      i += w.length; continue;
    }
    // Number
    const numM = line.slice(i).match(/^\d+(?:\.\d+)?/);
    if (numM) {
      tokens.push({ cls: 'tok-number', text: numM[0] });
      i += numM[0].length; continue;
    }
    // Punctuation / operator
    tokens.push({ cls: 'tok-punct', text: line[i] });
    i++;
  }
  return tokens;
}

function renderCode(code, lang = 'app') {
  const lines = code.split('\n');
  return lines.map((line, idx) => {
    const toks = tokenizeLine(line, lang);
    const spans = toks.map(t => `<span class="${t.cls}">${escHtml(t.text)}</span>`).join('');
    return `<div class="code-line"><span class="line-num">${idx + 1}</span><span>${spans}</span></div>`;
  }).join('');
}

function escHtml(s) {
  return s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');
}

// ── Navbar scroll effect ─────────────────────────────────────────────────────

window.addEventListener('scroll', () => {
  document.getElementById('navbar').classList.toggle('scrolled', window.scrollY > 20);
});

// ── Hero code tabs ───────────────────────────────────────────────────────────

let heroTypingTimer = null;
let heroTypedLen    = 0;

function setHeroTab(key) {
  document.querySelectorAll('#heroTabs .tab').forEach(t => {
    t.classList.toggle('active', t.dataset.tab === key);
  });
  const code = HERO_EXAMPLES[key];
  const el   = document.getElementById('heroCode');
  clearInterval(heroTypingTimer);
  heroTypedLen = 0;
  el.innerHTML = '';

  heroTypingTimer = setInterval(() => {
    heroTypedLen = Math.min(heroTypedLen + 4, code.length);
    el.innerHTML  = renderCode(code.slice(0, heroTypedLen));
    if (heroTypedLen >= code.length) clearInterval(heroTypingTimer);
  }, 12);
}

document.getElementById('heroTabs').addEventListener('click', e => {
  const btn = e.target.closest('.tab');
  if (btn) setHeroTab(btn.dataset.tab);
});

setHeroTab('hello');

// ── Targets ──────────────────────────────────────────────────────────────────

function langCode(id) {
  return id === 'csharp' ? 'csharp' : id;
}

function setTarget(id) {
  document.querySelectorAll('.target-tab').forEach(t => {
    t.classList.toggle('active', t.dataset.target === id);
  });
  const t = TARGETS[id];
  document.getElementById('targetFilename').textContent = `output.${t.ext}`;
  document.getElementById('targetCode').innerHTML = renderCode(t.code, langCode(id));

  const info = document.getElementById('targetInfo');
  info.innerHTML = `
    <div class="t-icon">${t.icon}</div>
    <div style="display:flex;align-items:center;gap:12px;margin-bottom:12px;">
      <h3 style="color:${t.color}">${t.name}</h3>
      <span class="badge" style="background:${t.color}18;color:${t.color};border:1px solid ${t.color}40;font-size:11px;">${t.badge}</span>
    </div>
    <p>${t.desc}</p>
    <div class="target-cmd"><span class="cmd-prefix">$ </span>${t.cmd}</div>
  `;
}

document.getElementById('targetTabs').addEventListener('click', e => {
  const btn = e.target.closest('.target-tab');
  if (btn) setTarget(btn.dataset.target);
});

setTarget('cpp');

// ── Examples ─────────────────────────────────────────────────────────────────

let activeExample = 0;

function renderExamples() {
  const sidebar = document.getElementById('examplesSidebar');
  sidebar.innerHTML = EXAMPLES.map((ex, i) => `
    <button class="example-btn${i === activeExample ? ' active' : ''}" data-idx="${i}">
      <div class="ex-title">${ex.title}</div>
      <div class="ex-file">${ex.file}</div>
    </button>
  `).join('');

  const ex = EXAMPLES[activeExample];
  document.getElementById('exampleFilename').textContent = ex.file;
  document.getElementById('exampleCode').innerHTML = renderCode(ex.code);
}

document.getElementById('examplesSidebar').addEventListener('click', e => {
  const btn = e.target.closest('.example-btn');
  if (!btn) return;
  activeExample = parseInt(btn.dataset.idx, 10);
  renderExamples();
});

renderExamples();

// ── Install steps ─────────────────────────────────────────────────────────────

function renderInstall() {
  const container = document.getElementById('installSteps');
  container.innerHTML = INSTALL_STEPS.map((s, i) => {
    const lines = s.lines.map(l => {
      const isComment = l.startsWith('#');
      return `<span class="cmd-line"><span class="${isComment ? 'cmd-comment' : 'cmd-prefix'}">${isComment ? '' : '$ '}</span>${escHtml(l)}</span>`;
    }).join('');
    const copyText = s.lines.filter(l => !l.startsWith('#')).join('\n');
    return `
      <div class="install-step">
        <div class="step-num">${i + 1}</div>
        <div class="step-body">
          <div class="step-title">${s.title}</div>
          <div class="step-code-wrap">
            <pre class="step-code">${lines}</pre>
            <button class="copy-btn" data-copy="${escHtml(copyText)}">Copy</button>
          </div>
        </div>
      </div>
    `;
  }).join('');

  document.querySelectorAll('.copy-btn').forEach(btn => {
    btn.addEventListener('click', () => {
      navigator.clipboard?.writeText(btn.dataset.copy).then(() => {
        btn.textContent = '✓ Copied';
        btn.classList.add('copied');
        setTimeout(() => { btn.textContent = 'Copy'; btn.classList.remove('copied'); }, 2000);
      });
    });
  });

  // Quick ref
  document.getElementById('quickrefGrid').innerHTML = QUICKREF.map(([cmd, desc]) =>
    `<div class="qr-item"><span class="qr-cmd">${escHtml(cmd)}</span><span class="qr-desc">${desc}</span></div>`
  ).join('');
}

renderInstall();

// Platform tabs (decorative — steps are the same; could be made per-platform)
document.getElementById('platformTabs').addEventListener('click', e => {
  const btn = e.target.closest('.platform-tab');
  if (!btn) return;
  document.querySelectorAll('.platform-tab').forEach(t => t.classList.toggle('active', t === btn));
});

// ── Footer year ───────────────────────────────────────────────────────────────

document.getElementById('year').textContent = new Date().getFullYear();

// ── Scroll fade-in observer ───────────────────────────────────────────────────

const observer = new IntersectionObserver(entries => {
  entries.forEach(e => { if (e.isIntersecting) { e.target.classList.add('fade-in'); observer.unobserve(e.target); } });
}, { threshold: 0.1 });

document.querySelectorAll('.feature-card, .install-step, .qr-item').forEach(el => observer.observe(el));
